#!/bin/bash

# WARNING: No LXC CALLS ALLOWED IN THIS SCRIPT.  THEY WILL DEADLOCK

# ARGS: container net up|down ...

[ "$2" = "net" ] && echo "/etc/lxc/lxc-portforward-helper $3 $1" | at -M now + 1 minutes 2>/dev/null

